#DROP TABLE PGA_SEQUENCE_TABLE;

DROP TABLE OCCUPANT_HISTORY;
DROP TABLE BED_PRICE_HISTORY;
DROP TABLE ACCOUNT;
DROP TABLE OCCUPANT_BED;
DROP TABLE OCCUPANT;
DROP TABLE BED_PRICE;
DROP TABLE BED;
DROP TABLE PRICE;
DROP TABLE USER;
DROP TABLE LOG;
DROP TABLE ROOM;
DROP TABLE PG;
select * from account;
select * from occupant_bed;
select * from occupant;
select * from account where FROM_DATE between '2012-01-01' AND '2012-01-31';
#CREATE TABLE PGA_SEQUENCE_TABLE (ID INTEGER NOT NULL, SEQUENCE_VALUE INTEGER, PRIMARY KEY (ID));
#CREATE SEQUENCE PGA_SEQ START 1 INCREMENT 1;

CREATE TABLE PG (
      PG_ID Integer PRIMARY KEY AUTO_INCREMENT,
      NAME VARCHAR(50) ,
      ADDRESS VARCHAR(50) NOT NULL,
      CATEGORY VARCHAR(10) NOT NULL);

CREATE TABLE USER (
      USER_ID Integer PRIMARY KEY AUTO_INCREMENT,
      PG_ID INTEGER NOT NULL ,
      NAME VARCHAR(50) NOT NULL,
      ROLE VARCHAR(50) NOT NULL,
      PASSWORD VARCHAR(50) NOT NULL
      );
      ALTER TABLE USER ADD CONSTRAINT USER_FK Foreign Key (PG_ID) REFERENCES PG (PG_ID);

      CREATE TABLE REGISTERED_USER (
      USER_ID Integer PRIMARY KEY AUTO_INCREMENT,
      FIRST_NAME VARCHAR(50) NOT NULL,
      LAST_NAME VARCHAR(50) NOT NULL,
      EMAIL VARCHAR(50) NOT NULL,
      PASSWORD VARCHAR(50) NOT NULL,
      MOBILE VARCHAR(50) NOT NULL
      );
      
      CREATE TABLE PG_STOCK(
      STOCK_ID Integer PRIMARY KEY AUTO_INCREMENT,
      ITEM VARCHAR(50) NOT NULL,
      QUANTITY VARCHAR(50) NOT NULL,
      PRICE INTEGER NOT NULL,
      PG_ID INTEGER NOT NULL 
       );
        ALTER TABLE PG_STOCK ADD CONSTRAINT STOCK_FK Foreign Key (PG_ID) REFERENCES PG (PG_ID);
      
      CREATE TABLE PG_USER(
      PG_ID INTEGER NOT NULL,
      USER_ID INTEGER NOT NULL,
      PRIMARY KEY (PG_ID, USER_ID));
      ALTER TABLE PG_USER ADD CONSTRAINT PG_ID_FK Foreign Key (PG_ID) REFERENCES PG (PG_ID);
      ALTER TABLE PG_USER ADD CONSTRAINT USER_ID_FK Foreign Key (USER_ID) REFERENCES USER (USER_ID);

      
CREATE TABLE LOG (
      LOG_ID Integer PRIMARY KEY AUTO_INCREMENT,
      PG_ID INTEGER NOT NULL,
      LOG VARCHAR(200),
      TYPE VARCHAR(50),
      DATE_CREATED VARCHAR(50)
      );
      ALTER TABLE LOG ADD CONSTRAINT LOG_FK Foreign Key (PG_ID) REFERENCES PG (PG_ID);
       
CREATE TABLE ROOM (
      ROOM_ID Integer PRIMARY KEY AUTO_INCREMENT,
      PG_ID INTEGER NOT NULL ,
      NAME VARCHAR(50),
      DATE_CREATED VARCHAR(50),
      DATE_DELETED VARCHAR(50)
      );
      ALTER TABLE ROOM ADD CONSTRAINT ROOM_FK Foreign Key (PG_ID) REFERENCES PG (PG_ID);
     ALTER TABLE ROOM DROP FOREIGN KEY ROOM_FK; 
     
CREATE TABLE BED (
      BED_ID Integer PRIMARY KEY AUTO_INCREMENT,
      PG_ID INTEGER NOT NULL ,
      OCCUPANT_ID INTEGER,
      ROOM_ID INTEGER NOT NULL ,
      DATE_CREATED VARCHAR(50) ,
      DATE_DELETED VARCHAR(50)
      );
      ALTER TABLE BED ADD CONSTRAINT BED_FK Foreign Key (ROOM_ID) REFERENCES ROOM (ROOM_ID);
      ALTER TABLE BED DROP FOREIGN KEY BED_FK;
CREATE TABLE PRICE (
      PRICE_ID Integer PRIMARY KEY AUTO_INCREMENT,
      PRICE Integer,
      PG_ID INTEGER NOT NULL,
      OCCURANCE VARCHAR(50)
      );

CREATE TABLE BED_PRICE (
      BED_ID INTEGER NOT NULL,
      PRICE_ID INTEGER NOT NULL,
      PRIMARY KEY (BED_ID, PRICE_ID)
);
ALTER TABLE BED_PRICE ADD CONSTRAINT BED_ID_FK Foreign Key (BED_ID) REFERENCES BED (BED_ID);
ALTER TABLE BED_PRICE ADD CONSTRAINT PRICE_ID_FK Foreign Key (PRICE_ID) REFERENCES PRICE (PRICE_ID);


CREATE TABLE BED_PRICE_HISTORY (
      BED_PRICE_ID Integer PRIMARY KEY AUTO_INCREMENT ,
      BED_ID INTEGER NOT NULL,
      PG_ID INTEGER NOT NULL,
      PRICE_ID INTEGER NOT NULL,
      EFFECTIVE_FROM DATE,
      EFFECTIVE_TO DATE
);

CREATE TABLE OCCUPANT (
      OCCUPANT_ID Integer PRIMARY KEY AUTO_INCREMENT ,
      PG_ID INTEGER NOT NULL,
      BED_ID INTEGER NOT NULL,
      NAME VARCHAR(50) ,
      MOBILE INTEGER,
      ADDRESS VARCHAR(50) NOT NULL,
      COMPANY VARCHAR(50),
      COLLEGE VARCHAR(50),
      IDCARD VARCHAR(20),
      ID_NUM VARCHAR(20),
      CITY VARCHAR(25),
      EMAIL VARCHAR(30) NOT NULL,
      IMAGE LONGBLOB
      );
       ALTER TABLE OCCUPANT ADD CONSTRAINT OCCUPANT_pgid_FK Foreign Key (PG_ID) REFERENCES PG (PG_ID);
     ALTER TABLE OCCUPANT ADD CONSTRAINT OCCUPANT_Bedid_FK Foreign Key (BED_ID) REFERENCES BED (BED_ID);
      
CREATE TABLE OCCUPANT_BED (
      OCCUPANT_BED_ID Integer PRIMARY KEY AUTO_INCREMENT ,
      OCCUPANT_ID INTEGER NOT NULL,
      BED_ID INTEGER NOT NULL,
      PRICE_ID INTEGER NOT NULL
     );
     ALTER TABLE OCCUPANT_BED ADD CONSTRAINT OCCUPANT_BED_BED_FK Foreign Key (BED_ID) REFERENCES BED (BED_ID);
     ALTER TABLE OCCUPANT_BED ADD CONSTRAINT OCCUPANT_BED_OCCUPANT_FK Foreign Key (OCCUPANT_ID) REFERENCES OCCUPANT (OCCUPANT_ID);
     ALTER TABLE OCCUPANT_BED ADD CONSTRAINT OCCUPANT_BED_PRICE_FK Foreign Key (PRICE_ID) REFERENCES PRICE (PRICE_ID);
   
     INSERT INTO ACCOUNT VALUES()
     
CREATE TABLE ACCOUNT (
      ACCOUNT_ID Integer PRIMARY KEY AUTO_INCREMENT ,
      OCCUPANT_ID INTEGER NOT NULL,
      PG_ID INTEGER NOT NULL,
      FROM_DATE DATE,
      TO_DATE DATE,
      DUES INTEGER NOT NULL,
      PAYMENT INTEGER NOT NULL,
      PAYMENT_DATE DATE,
      NOTIFICATION VARCHAR(50)
);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_FK Foreign Key (OCCUPANT_ID) REFERENCES OCCUPANT (OCCUPANT_ID);

CREATE TABLE OCCUPANT_HISTORY (
      HISTORY_ID Integer PRIMARY KEY AUTO_INCREMENT ,
      PG_ID INTEGER NOT NULL,
      OCCUPANT_ID INTEGER NOT NULL,
      ROOM_ID INTEGER NOT NULL,
      BED_ID INTEGER NOT NULL,
      ENTRY_DATE DATE,
      EXIT_DATE DATE
);
ALTER TABLE OCCUPANT_HISTORY ADD CONSTRAINT OCCUPANT_HISTORY_FK Foreign Key (OCCUPANT_ID) REFERENCES OCCUPANT (OCCUPANT_ID);
